alpha: 0.35
arch: NestedUNet
batch_size: 1
beta1: 0.9
beta2: 0.999
dataset: ICA
deep_supervision: false
early_stopping: -1
epochs: 2000
factor: 0.1
gamma: 0.6666666666666666
img_ext: .png
input_channels: 3
input_h: 512
input_w: 512
loss: BCEDiceLoss
lr: 1.0e-06
mask_ext: .png
milestones: 1,2
min_lr: 1.0e-08
momentum: 0.9
name: ICA_NestedUNet_woDS
nesterov: false
num_classes: 1
num_workers: 2
optimizer: Adam
patience: 2
sample_freq: 5
scheduler: ConstantLR
sigma: 0.1
val_set_ratio: 0.1
weight_decay: 0.0001
